fix some unintended compiler error
if don't fix, the test will generate undesired .h which will be used in
later compile, some will cause build failed

see *.h{1,2} for details, run following cmd to see difference:
  diff -uprN <(more *.h1|sed 's:\.h1$:.h:g') <(more *.h2|sed 's:\.h2$:.h:g')

found by using clang 18 with CFLAGS: -Wall -Wextra

chkshsgr.c trycpp.c trypoll.c tryshsgr.c tryulong64.c:
  error: call to undeclared function 'getgroups'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

tryflock.c trysgact.c trysgprm.c trywaitp.c:
  error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]